// Gerado a partir da planilha de fichas técnicas (FT_INTEGRADA_SMASH_STATION_v2_PRE_OS.xlsx).
// Não editar à mão — se a planilha mudar, regenere este arquivo.

export interface InsumoSeed {
  nome: string;
  unidadeConsumo: string;
  custoMedio: number;
}

export interface IngredienteSeed {
  produtoNome: string;
  quantidade: number;
  unidade: string;
}

export interface ItemCardapioSeed {
  nome: string;
  categoria: string;
  precoVenda: number;
  custoTotalCalculado: number;
  ingredientes: IngredienteSeed[];
}

export const insumos: InsumoSeed[] = [
  { nome: 'Pão para smash', unidadeConsumo: 'unidade', custoMedio: 1.34 },
  { nome: 'Carne bovina', unidadeConsumo: 'g', custoMedio: 34.9 },
  { nome: 'Alface', unidadeConsumo: 'g', custoMedio: 14.285714 },
  { nome: 'Tomate Carmem', unidadeConsumo: 'g', custoMedio: 11.25 },
  { nome: 'Cebola', unidadeConsumo: 'g', custoMedio: 5.0 },
  { nome: 'Picles de pepino', unidadeConsumo: 'g', custoMedio: 45.0 },
  { nome: 'Ketchup', unidadeConsumo: 'g', custoMedio: 17.77 },
  { nome: 'Mostarda', unidadeConsumo: 'g', custoMedio: 23.2 },
  { nome: 'Bacon', unidadeConsumo: 'g', custoMedio: 41.87 },
  { nome: 'Leite integral', unidadeConsumo: 'ml', custoMedio: 5.49 },
  { nome: 'Sal', unidadeConsumo: 'g', custoMedio: 3.5 },
  { nome: 'Batata palito', unidadeConsumo: 'g', custoMedio: 17.628 },
  { nome: 'Ovo in natura', unidadeConsumo: 'unidade', custoMedio: 1.0 },
  { nome: 'Embalagem hambúrguer', unidadeConsumo: 'unidade', custoMedio: 1.23 },
  { nome: 'Embalagem batata', unidadeConsumo: 'unidade', custoMedio: 0.76 },
  { nome: 'Papel embrulho', unidadeConsumo: 'unidade', custoMedio: 0.15 },
  { nome: 'Óleo de algodão', unidadeConsumo: 'ml', custoMedio: 11.098734 },
  { nome: 'Cebola roxa', unidadeConsumo: 'g', custoMedio: 16.25 },
  { nome: 'Banha Suína', unidadeConsumo: 'g', custoMedio: 17.57 },
  { nome: 'Almofada Queijo Gouda', unidadeConsumo: 'g', custoMedio: 78.556667 },
  { nome: 'Queijo Cheddar Processado', unidadeConsumo: 'g', custoMedio: 37.484581 },
  { nome: 'Ovomaltine', unidadeConsumo: 'g', custoMedio: 43.36 },
  { nome: 'Creme americano', unidadeConsumo: 'ml', custoMedio: 11.4 },
  { nome: 'Calda morango', unidadeConsumo: 'ml', custoMedio: 35.0 },
  { nome: 'Cobertura chocolate', unidadeConsumo: 'ml', custoMedio: 24.19 },
  { nome: 'Cobertura morango', unidadeConsumo: 'ml', custoMedio: 17.55 },
  { nome: 'Tampa', unidadeConsumo: 'unidade', custoMedio: 0.34 },
  { nome: 'Hamburguer Vegetariano', unidadeConsumo: 'g', custoMedio: 7.0 },
  { nome: 'Nuggets', unidadeConsumo: 'g', custoMedio: 25.0 },
  { nome: 'Copo 440ml', unidadeConsumo: 'unidade', custoMedio: 0.42 },
  { nome: 'Canudo Milk-Shake', unidadeConsumo: 'unidade', custoMedio: 0.13 },
  { nome: 'sal parrilla', unidadeConsumo: 'g', custoMedio: 12.78 },
  { nome: 'Maionese de Bacon', unidadeConsumo: 'g', custoMedio: 17.040672 },
  { nome: 'American Cheese 1', unidadeConsumo: 'g', custoMedio: 35.662 },
  { nome: 'Maionese Verde', unidadeConsumo: 'g', custoMedio: 16.119443 },
  { nome: 'Cheddar da Casa', unidadeConsumo: 'g', custoMedio: 31.516407 },
  { nome: 'Cebola Caramelizada', unidadeConsumo: 'g', custoMedio: 6.245 },
  { nome: 'Molho Tasty', unidadeConsumo: 'g', custoMedio: 16.096175 },
  { nome: 'Molho Big', unidadeConsumo: 'g', custoMedio: 21.15723 },
  { nome: 'Molho Gouda', unidadeConsumo: 'g', custoMedio: 5.596111 },
  { nome: 'sal batata', unidadeConsumo: 'g', custoMedio: 9.326389 },
];

export const itensCardapio: ItemCardapioSeed[] = [
  {
    nome: 'Cheese Burger',
    categoria: 'Lanches',
    precoVenda: 25.0,
    custoTotalCalculado: 5.45249,
    ingredientes: [
      { produtoNome: 'Pão para smash', quantidade: 1.0, unidade: 'unidade' },
      { produtoNome: 'Carne bovina', quantidade: 80.0, unidade: 'g' },
      { produtoNome: 'American Cheese 1', quantidade: 30.0, unidade: 'g' },
      { produtoNome: 'Papel embrulho', quantidade: 1.0, unidade: 'unidade' },
      { produtoNome: 'Banha Suína', quantidade: 5.0, unidade: 'g' },
      { produtoNome: 'sal parrilla', quantidade: 1.0, unidade: 'g' },
    ],
  },
  {
    nome: 'Cheese Burger Duplo',
    categoria: 'Lanches',
    precoVenda: 33.0,
    custoTotalCalculado: 9.32713,
    ingredientes: [
      { produtoNome: 'Pão para smash', quantidade: 1.0, unidade: 'unidade' },
      { produtoNome: 'Carne bovina', quantidade: 80.0, unidade: 'g' },
      { produtoNome: 'American Cheese 1', quantidade: 30.0, unidade: 'g' },
      { produtoNome: 'Papel embrulho', quantidade: 1.0, unidade: 'unidade' },
      { produtoNome: 'Banha Suína', quantidade: 5.0, unidade: 'g' },
      { produtoNome: 'sal parrilla', quantidade: 2.0, unidade: 'g' },
      { produtoNome: 'Carne bovina', quantidade: 80.0, unidade: 'g' },
      { produtoNome: 'American Cheese 1', quantidade: 30.0, unidade: 'g' },
    ],
  },
  {
    nome: 'Quarter',
    categoria: 'Lanches',
    precoVenda: 29.0,
    custoTotalCalculado: 6.363482304,
    ingredientes: [
      { produtoNome: 'Pão para smash', quantidade: 1.0, unidade: 'unidade' },
      { produtoNome: 'Carne bovina', quantidade: 80.0, unidade: 'g' },
      { produtoNome: 'American Cheese 1', quantidade: 30.0, unidade: 'g' },
      { produtoNome: 'Picles de pepino', quantidade: 10.0, unidade: 'g' },
      { produtoNome: 'Ketchup', quantidade: 6.0, unidade: 'g' },
      { produtoNome: 'Mostarda', quantidade: 4.0, unidade: 'g' },
      { produtoNome: 'Molho Big', quantidade: 10.0, unidade: 'g' },
      { produtoNome: 'Cebola', quantidade: 10.0, unidade: 'g' },
      { produtoNome: 'sal parrilla', quantidade: 1.0, unidade: 'g' },
      { produtoNome: 'Papel embrulho', quantidade: 1.0, unidade: 'unidade' },
      { produtoNome: 'Banha Suína', quantidade: 5.0, unidade: 'g' },
    ],
  },
  {
    nome: 'Cheddar Bacon',
    categoria: 'Lanches',
    precoVenda: 29.0,
    custoTotalCalculado: 6.39837894,
    ingredientes: [
      { produtoNome: 'Pão para smash', quantidade: 1.0, unidade: 'unidade' },
      { produtoNome: 'Carne bovina', quantidade: 80.0, unidade: 'g' },
      { produtoNome: 'Cheddar da Casa', quantidade: 30.0, unidade: 'g' },
      { produtoNome: 'Bacon', quantidade: 20.0, unidade: 'g' },
      { produtoNome: 'Maionese de Bacon', quantidade: 10.0, unidade: 'g' },
      { produtoNome: 'Banha Suína', quantidade: 5.0, unidade: 'g' },
      { produtoNome: 'Papel embrulho', quantidade: 1.0, unidade: 'unidade' },
      { produtoNome: 'Cebola Caramelizada', quantidade: 10.0, unidade: 'g' },
      { produtoNome: 'sal parrilla', quantidade: 1.0, unidade: 'g' },
    ],
  },
  {
    nome: 'Cheese Salada',
    categoria: 'Lanches',
    precoVenda: 29.0,
    custoTotalCalculado: 6.236666033,
    ingredientes: [
      { produtoNome: 'Pão para smash', quantidade: 1.0, unidade: 'unidade' },
      { produtoNome: 'American Cheese 1', quantidade: 30.0, unidade: 'g' },
      { produtoNome: 'Molho Tasty', quantidade: 10.0, unidade: 'g' },
      { produtoNome: 'Alface', quantidade: 20.0, unidade: 'g' },
      { produtoNome: 'Tomate Carmem', quantidade: 30.0, unidade: 'g' },
      { produtoNome: 'Carne bovina', quantidade: 80.0, unidade: 'g' },
      { produtoNome: 'Banha Suína', quantidade: 5.0, unidade: 'g' },
      { produtoNome: 'Papel embrulho', quantidade: 1.0, unidade: 'unidade' },
      { produtoNome: 'sal parrilla', quantidade: 1.0, unidade: 'g' },
    ],
  },
  {
    nome: 'Cheese Egg',
    categoria: 'Lanches',
    precoVenda: 27.0,
    custoTotalCalculado: 6.622896717,
    ingredientes: [
      { produtoNome: 'Pão para smash', quantidade: 1.0, unidade: 'unidade' },
      { produtoNome: 'American Cheese 1', quantidade: 30.0, unidade: 'g' },
      { produtoNome: 'Maionese de Bacon', quantidade: 10.0, unidade: 'g' },
      { produtoNome: 'Carne bovina', quantidade: 80.0, unidade: 'g' },
      { produtoNome: 'Banha Suína', quantidade: 5.0, unidade: 'g' },
      { produtoNome: 'Ovo in natura', quantidade: 1.0, unidade: 'unidade' },
      { produtoNome: 'Papel embrulho', quantidade: 1.0, unidade: 'unidade' },
      { produtoNome: 'sal parrilla', quantidade: 1.0, unidade: 'g' },
    ],
  },
  {
    nome: 'Big Smash',
    categoria: 'Lanches',
    precoVenda: 37.0,
    custoTotalCalculado: 9.540734472,
    ingredientes: [
      { produtoNome: 'Pão para smash', quantidade: 1.0, unidade: 'unidade' },
      { produtoNome: 'Queijo Cheddar Processado', quantidade: 15.0, unidade: 'g' },
      { produtoNome: 'Molho Big', quantidade: 15.0, unidade: 'g' },
      { produtoNome: 'Carne bovina', quantidade: 80.0, unidade: 'g' },
      { produtoNome: 'Banha Suína', quantidade: 5.0, unidade: 'g' },
      { produtoNome: 'Alface', quantidade: 40.0, unidade: 'g' },
      { produtoNome: 'Cebola', quantidade: 8.0, unidade: 'g' },
      { produtoNome: 'Carne bovina', quantidade: 80.0, unidade: 'g' },
      { produtoNome: 'Picles de pepino', quantidade: 10.0, unidade: 'g' },
      { produtoNome: 'sal parrilla', quantidade: 2.0, unidade: 'g' },
      { produtoNome: 'Queijo Cheddar Processado', quantidade: 15.0, unidade: 'g' },
    ],
  },
  {
    nome: 'Tasty Smash',
    categoria: 'Lanches',
    precoVenda: 37.0,
    custoTotalCalculado: 8.790932535,
    ingredientes: [
      { produtoNome: 'Pão para smash', quantidade: 1.0, unidade: 'unidade' },
      { produtoNome: 'Queijo Cheddar Processado', quantidade: 15.0, unidade: 'g' },
      { produtoNome: 'Molho Tasty', quantidade: 30.0, unidade: 'g' },
      { produtoNome: 'Carne bovina', quantidade: 80.0, unidade: 'g' },
      { produtoNome: 'Banha Suína', quantidade: 5.0, unidade: 'g' },
      { produtoNome: 'Alface', quantidade: 40.0, unidade: 'g' },
      { produtoNome: 'Cebola roxa', quantidade: 10.0, unidade: 'g' },
      { produtoNome: 'Carne bovina', quantidade: 80.0, unidade: 'g' },
      { produtoNome: 'Tomate Carmem', quantidade: 30.0, unidade: 'g' },
      { produtoNome: 'sal parrilla', quantidade: 2.0, unidade: 'g' },
      { produtoNome: 'Queijo Cheddar Processado', quantidade: 15.0, unidade: 'g' },
    ],
  },
  {
    nome: 'Vegetariano',
    categoria: 'Lanches',
    precoVenda: 28.0,
    custoTotalCalculado: 11.28688603,
    ingredientes: [
      { produtoNome: 'Pão para smash', quantidade: 1.0, unidade: 'unidade' },
      { produtoNome: 'American Cheese 1', quantidade: 30.0, unidade: 'g' },
      { produtoNome: 'Molho Tasty', quantidade: 10.0, unidade: 'g' },
      { produtoNome: 'Hamburguer Vegetariano', quantidade: 1000.0, unidade: 'g' },
      { produtoNome: 'Banha Suína', quantidade: 5.0, unidade: 'g' },
      { produtoNome: 'Embalagem hambúrguer', quantidade: 1.0, unidade: 'unidade' },
      { produtoNome: 'Alface', quantidade: 20.0, unidade: 'g' },
      { produtoNome: 'Tomate Carmem', quantidade: 10.0, unidade: 'g' },
    ],
  },
  {
    nome: 'Batata Palito',
    categoria: 'Acompanhamentos',
    precoVenda: 25.0,
    custoTotalCalculado: 6.092169671,
    ingredientes: [
      { produtoNome: 'Batata palito', quantidade: 200.0, unidade: 'g' },
      { produtoNome: 'Óleo de algodão', quantidade: 115.0, unidade: 'ml' },
      { produtoNome: 'Embalagem batata', quantidade: 1.0, unidade: 'unidade' },
      { produtoNome: 'sal batata', quantidade: 5.0, unidade: 'g' },
      { produtoNome: 'Maionese Verde', quantidade: 30.0, unidade: 'g' },
    ],
  },
  {
    nome: 'Nuggets',
    categoria: 'Acompanhamentos',
    precoVenda: 28.0,
    custoTotalCalculado: 8.246071342,
    ingredientes: [
      { produtoNome: 'Nuggets', quantidade: 223.0, unidade: 'g' },
      { produtoNome: 'Óleo de algodão', quantidade: 115.0, unidade: 'ml' },
      { produtoNome: 'Embalagem batata', quantidade: 1.0, unidade: 'unidade' },
      { produtoNome: 'Molho Big', quantidade: 30.0, unidade: 'g' },
    ],
  },
  {
    nome: 'Almofada Gouda',
    categoria: 'Acompanhamentos',
    precoVenda: 40.0,
    custoTotalCalculado: 17.9330711,
    ingredientes: [
      { produtoNome: 'Almofada Queijo Gouda', quantidade: 200.0, unidade: 'g' },
      { produtoNome: 'Óleo de algodão', quantidade: 115.0, unidade: 'ml' },
      { produtoNome: 'Embalagem batata', quantidade: 1.0, unidade: 'unidade' },
      { produtoNome: 'Sal', quantidade: 5.0, unidade: 'g' },
      { produtoNome: 'Molho Gouda', quantidade: 30.0, unidade: 'g' },
    ],
  },
  {
    nome: 'Milkshake Ovomaltine',
    categoria: 'Bebidas',
    precoVenda: 25.0,
    custoTotalCalculado: 6.33735,
    ingredientes: [
      { produtoNome: 'Creme americano', quantidade: 250.0, unidade: 'ml' },
      { produtoNome: 'Leite integral', quantidade: 25.0, unidade: 'ml' },
      { produtoNome: 'Ovomaltine', quantidade: 40.0, unidade: 'g' },
      { produtoNome: 'Cobertura chocolate', quantidade: 30.0, unidade: 'ml' },
      { produtoNome: 'Copo 440ml', quantidade: 1.0, unidade: 'unidade' },
      { produtoNome: 'Tampa', quantidade: 1.0, unidade: 'unidade' },
      { produtoNome: 'Canudo Milk-Shake', quantidade: 1.0, unidade: 'unidade' },
    ],
  },
  {
    nome: 'Milkshake Morango',
    categoria: 'Bebidas',
    precoVenda: 25.0,
    custoTotalCalculado: 7.90375,
    ingredientes: [
      { produtoNome: 'Creme americano', quantidade: 250.0, unidade: 'ml' },
      { produtoNome: 'Leite integral', quantidade: 25.0, unidade: 'ml' },
      { produtoNome: 'Calda morango', quantidade: 100.0, unidade: 'ml' },
      { produtoNome: 'Cobertura morango', quantidade: 30.0, unidade: 'ml' },
      { produtoNome: 'Copo 440ml', quantidade: 1.0, unidade: 'unidade' },
      { produtoNome: 'Tampa', quantidade: 1.0, unidade: 'unidade' },
      { produtoNome: 'Canudo Milk-Shake', quantidade: 1.0, unidade: 'unidade' },
    ],
  },
  {
    nome: 'Combo Cheese',
    categoria: 'Combos',
    precoVenda: 50.0,
    custoTotalCalculado: 14.43465967,
    ingredientes: [],
  },
  {
    nome: 'Combo Simples',
    categoria: 'Combos',
    precoVenda: 54.0,
    custoTotalCalculado: 15.34565197,
    ingredientes: [],
  },
  {
    nome: 'Combo Cheese Duplo',
    categoria: 'Combos',
    precoVenda: 58.0,
    custoTotalCalculado: 18.92216967,
    ingredientes: [],
  },
  {
    nome: 'Combo Duplo',
    categoria: 'Combos',
    precoVenda: 61.0,
    custoTotalCalculado: 19.86216967,
    ingredientes: [],
  },
];
